version: "3.4"
services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    hostname: qbittorrent
    environment:
      - PGID=1000 #需要自行修改填入
      - PUID=1000 #需要自行修改填入
      - WEBUI_PORT=8989
      - TZ=Asia/Shanghai
    volumes:
      - ./qb_config:/config
      - your_anime_path:/downloads # 注意 修改此处为自己存放动漫的目录,ab 内下载路径填写downloads
    networks:
      - host
    restart: unless-stopped

  AutoBangumi:
    image: "ghcr.io/estrellaxd/auto_bangumi:latest"
    container_name: AutoBangumi
    depends_on:
      - qbittorrent
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    networks:
      - host
    dns:
      - 223.5.5.5
    restart: unless-stopped
    environment:
      - AB_METHOD=Advance
      - AB_DOWNLOADER_HOST=127.0.0.1:8989 #如8989被修改,请修改为相应端口
      - AB_DOWNLOADER_USERNAME=admin
      - AB_DOWNLOADER_PASSWORD=adminadmin
      - AB_DOWNLOAD_PATH=/downloads #qbittorrent 映射的地址，否者可能提示下载失败
