version = 1

exclude_patterns = ["*.sh"]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/maikirakiwi/Goto_Bangumi"
  dependencies_vendored = true